{
  "Uuid": "51c34203-1421-41bb-bda3-b285be16a6d6",
  "IsCustomNode": false,
  "Description": "",
  "Name": "bounding box test",
  "ElementResolver": {
    "ResolutionMap": {}
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double",
      "Id": "7d9ea90857f249c2b98bb7d7f578b3a6",
      "Inputs": [
        {
          "Id": "62ff50bf394b41ae951a0f98eb7d2f5d",
          "Name": "x",
          "Description": "X coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "c5210c201eea452f9ed4c4336143983c",
          "Name": "y",
          "Description": "Y coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "b05b65b169554c6a9afbee8b20d9ba14",
          "Name": "z",
          "Description": "Z coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "378ef6a413f343c685b7f7bff96c2957",
          "Name": "Point",
          "Description": "Point created by coordinates",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Form a Point given 3 cartesian coordinates\n\nPoint.ByCoordinates (x: double = 0, y: double = 0, z: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double",
      "Id": "f2d475585fbb462da459f8c67652c01c",
      "Inputs": [
        {
          "Id": "0fc0721e7ef84d518efdf1421896eaf2",
          "Name": "x",
          "Description": "X coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "1c5438a00bcf4ab4a5640aaf0a6b494f",
          "Name": "y",
          "Description": "Y coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "4f627b5508a44f5a8f45df5ca520c217",
          "Name": "z",
          "Description": "Z coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "e141c3f10e654156ad4a02a26124860d",
          "Name": "Point",
          "Description": "Point created by coordinates",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Form a Point given 3 cartesian coordinates\n\nPoint.ByCoordinates (x: double = 0, y: double = 0, z: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "10;",
      "Id": "5401f18c26a14cf79512d750f23a2f99",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "c9a62d9b5ab240c1b881fb61e999a1b1",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.BoundingBox.ByCorners@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point",
      "Id": "d5e6669ab735421a89fc523340313585",
      "Inputs": [
        {
          "Id": "e14e1b7645d5486b9cdf27c3529ec443",
          "Name": "min",
          "Description": "Point\nDefault value : Autodesk.DesignScript.Geometry.Point.ByCoordinates(0, 0, 0)",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "5847dedf1829494c8b4e8e4888985a58",
          "Name": "max",
          "Description": "Point\nDefault value : Autodesk.DesignScript.Geometry.Point.ByCoordinates(1, 1, 1)",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "e09a1c556e184aeeb6b5367b644a6088",
          "Name": "BoundingBox",
          "Description": "BoundingBox",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Creates the an axis-aligned BoundingBox spanning between the minimum Point and the maximum Point.\n\nBoundingBox.ByCorners (min: Point = Autodesk.DesignScript.Geometry.Point.ByCoordinates(0, 0, 0), max: Point = Autodesk.DesignScript.Geometry.Point.ByCoordinates(1, 1, 1)): BoundingBox"
    },
    {
      "ConcreteType": "PythonNodeModels.PythonNode, PythonNodeModels",
      "NodeType": "PythonScriptNode",
      "Code": "# Load the Python Standard and DesignScript Libraries\r\nimport sys\r\nimport clr\r\nclr.AddReference('ProtoGeometry')\r\nfrom Autodesk.DesignScript.Geometry import *\r\n\r\nclr.AddReference('RevitAPI')\r\nfrom Autodesk.Revit.DB import *\r\nfrom Autodesk.Revit.DB.Structure import *\r\n\r\nclr.AddReference('RevitAPIUI')\r\nfrom Autodesk.Revit.UI import *\r\n\r\nclr.AddReference('System')\r\nfrom System.Collections.Generic import List\r\n\r\nclr.AddReference('RevitNodes')\r\nimport Revit\r\nclr.ImportExtensions(Revit.GeometryConversion)\r\nclr.ImportExtensions(Revit.Elements)\r\n\r\n# The inputs to this node will be stored as a list in the IN variables.\r\ndataEnteringNode = IN\r\n\r\n# Place your code below this line\r\nbbox = IN[0].ToRevitType()\r\n# Assign your output to the OUT variable.\r\nOUT = IN[0], bbox.ToProtoType()",
      "Engine": "CPython3",
      "EngineName": "CPython3",
      "VariableInputPorts": true,
      "Id": "ed11ba8389c940ffa2a2e3d6987c821a",
      "Inputs": [
        {
          "Id": "f05bfc61502d43938ab7c3813496d65f",
          "Name": "IN[0]",
          "Description": "Input #0",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "c2d594291abc452d85f436b1dcedc66b",
          "Name": "OUT",
          "Description": "Result of the python script",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Runs an embedded Python script."
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.BoundingBox.ToCuboid",
      "Id": "f771e1941c5a49e4b56ed2db5fcb6f25",
      "Inputs": [
        {
          "Id": "f95e909b3da74ef986712e3ede9d49b7",
          "Name": "boundingBox",
          "Description": "Autodesk.DesignScript.Geometry.BoundingBox",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "5c49c08ab62d43d181ad62edfef850c7",
          "Name": "Cuboid",
          "Description": "Returns cuboid representation of the bounding box.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get the bounding box as a solid cuboid.\n\nBoundingBox.ToCuboid ( ): Cuboid"
    }
  ],
  "Connectors": [
    {
      "Start": "378ef6a413f343c685b7f7bff96c2957",
      "End": "e14e1b7645d5486b9cdf27c3529ec443",
      "Id": "8315df877ab146a48c047a97e7527c1b",
      "IsHidden": "False"
    },
    {
      "Start": "e141c3f10e654156ad4a02a26124860d",
      "End": "5847dedf1829494c8b4e8e4888985a58",
      "Id": "548f708d2bc742c59153cf16578b5ca6",
      "IsHidden": "False"
    },
    {
      "Start": "c9a62d9b5ab240c1b881fb61e999a1b1",
      "End": "0fc0721e7ef84d518efdf1421896eaf2",
      "Id": "c1cf17a0e74148d0a437219c04a20a4d",
      "IsHidden": "False"
    },
    {
      "Start": "c9a62d9b5ab240c1b881fb61e999a1b1",
      "End": "1c5438a00bcf4ab4a5640aaf0a6b494f",
      "Id": "efaccc6e49614297824068a23bce7d1b",
      "IsHidden": "False"
    },
    {
      "Start": "c9a62d9b5ab240c1b881fb61e999a1b1",
      "End": "4f627b5508a44f5a8f45df5ca520c217",
      "Id": "84ea6b732b3745a0b89d0e955f2fcdd9",
      "IsHidden": "False"
    },
    {
      "Start": "e09a1c556e184aeeb6b5367b644a6088",
      "End": "f05bfc61502d43938ab7c3813496d65f",
      "Id": "c7b922f92cb84d2cb0dfe5de503a8a91",
      "IsHidden": "False"
    },
    {
      "Start": "c2d594291abc452d85f436b1dcedc66b",
      "End": "f95e909b3da74ef986712e3ede9d49b7",
      "Id": "b98aeed75f0941288d899112b00e59ce",
      "IsHidden": "False"
    }
  ],
  "Dependencies": [],
  "NodeLibraryDependencies": [],
  "Thumbnail": "",
  "GraphDocumentationURL": null,
  "ExtensionWorkspaceData": [
    {
      "ExtensionGuid": "28992e1d-abb9-417f-8b1b-05e053bee670",
      "Name": "Properties",
      "Version": "2.16",
      "Data": {}
    },
    {
      "ExtensionGuid": "DFBD9CC0-DB40-457A-939E-8C8555555A9D",
      "Name": "Generative Design",
      "Version": "3.0",
      "Data": {}
    }
  ],
  "Author": "",
  "Linting": {
    "activeLinter": "None",
    "activeLinterId": "7b75fb44-43fd-4631-a878-29f4d5d8399a",
    "warningCount": 0,
    "errorCount": 0
  },
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": true,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.16.1.2727",
      "RunType": "Manual",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Background Preview",
      "EyeX": 30.047531127929688,
      "EyeY": 27.112224578857422,
      "EyeZ": 38.606124877929688,
      "LookX": -37.580635070800781,
      "LookY": -25.99029541015625,
      "LookZ": -39.864765167236328,
      "UpX": -0.15430600941181183,
      "UpY": 0.97437012195587158,
      "UpZ": -0.16368463635444641
    },
    "ConnectorPins": [],
    "NodeViews": [
      {
        "Name": "Point.ByCoordinates",
        "ShowGeometry": true,
        "Id": "7d9ea90857f249c2b98bb7d7f578b3a6",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 267.0,
        "Y": 267.0
      },
      {
        "Name": "Point.ByCoordinates",
        "ShowGeometry": true,
        "Id": "f2d475585fbb462da459f8c67652c01c",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 272.0,
        "Y": 532.0
      },
      {
        "Name": "Code Block",
        "ShowGeometry": true,
        "Id": "5401f18c26a14cf79512d750f23a2f99",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 4.0,
        "Y": 625.0
      },
      {
        "Name": "BoundingBox.ByCorners",
        "ShowGeometry": true,
        "Id": "d5e6669ab735421a89fc523340313585",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 587.5,
        "Y": 325.0
      },
      {
        "Name": "Python Script",
        "ShowGeometry": true,
        "Id": "ed11ba8389c940ffa2a2e3d6987c821a",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1010.0328043445272,
        "Y": 205.60599128698288
      },
      {
        "Name": "BoundingBox.ToCuboid",
        "ShowGeometry": true,
        "Id": "f771e1941c5a49e4b56ed2db5fcb6f25",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1301.8697939215037,
        "Y": 279.49231850465446
      }
    ],
    "Annotations": [],
    "X": -2049.2794523921184,
    "Y": -430.48473339399686,
    "Zoom": 1.8354164893775797
  }
}