{
  "Uuid": "5a743b41-b8f6-4d97-8840-dbd039700214",
  "IsCustomNode": false,
  "Description": "",
  "Name": "20211017_좌표계변환테스트",
  "ElementResolver": {
    "ResolutionMap": {
      "Point.ByCoordinates": {
        "Key": "Autodesk.DesignScript.Geometry.Point",
        "Value": "ProtoGeometry.dll"
      },
      "Point": {
        "Key": "Autodesk.DesignScript.Geometry.Point",
        "Value": "ProtoGeometry.dll"
      }
    }
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.CoordinateSystem.ByPlane@Autodesk.DesignScript.Geometry.Plane",
      "Id": "8709a61bede04d499643d6152eb8306f",
      "Inputs": [
        {
          "Id": "8ea06d58a3ba46359a23c92fd7f47149",
          "Name": "plane",
          "Description": "Plane\n기본값 : Autodesk.DesignScript.Geometry.Plane.XY()",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "b0898bf4864c4537813c95a07272ca1a",
          "Name": "CoordinateSystem",
          "Description": "CoordinateSystem",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "입력 평면 원점을 원점으로 하고 X 및 Y축이 평면에 배치되고 평면 X 및 Y축과 일치하는 CoordinateSystem을 만듭니다.\n\nCoordinateSystem.ByPlane (plane: Plane = Autodesk.DesignScript.Geometry.Plane.XY()): CoordinateSystem"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Plane.ByBestFitThroughPoints@Autodesk.DesignScript.Geometry.Point[]",
      "Id": "8c0d13e9f4d94603a8b97a3c7e8fcde4",
      "Inputs": [
        {
          "Id": "eadfe5dff8454c01984d43280ff58daf",
          "Name": "points",
          "Description": "List of points to define plane\n\nPoint[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "7c11aee3e4314cb3abc3cc0cd3ebe509",
          "Name": "Plane",
          "Description": "Plane created by best fit through points",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "평면을 입력 점에 맞춥니다. 기본적으로 3D 산점도 맞춤입니다.\n\nPlane.ByBestFitThroughPoints (points: Point[]): Plane"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "Point.ByCoordinates(0,0,0);\nPoint.ByCoordinates(0,10,20);\nPoint.ByCoordinates(0,20,30);\nPoint.ByCoordinates(0,30,40);\nPoint.ByCoordinates(0,40,0);",
      "Id": "5da7d3f3bb72442bb160b8f9ce4772a2",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "636083cd8ab44af7ad777c5a7348b31a",
          "Name": "",
          "Description": "선 1의 표현식 값",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "fb8e311a6f484d46bb8be142a68d75f7",
          "Name": "",
          "Description": "선 2의 표현식 값",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "239feb11b141466594bd8fa425590541",
          "Name": "",
          "Description": "선 3의 표현식 값",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "f7de09c4355a49a38b434bc1bdd44742",
          "Name": "",
          "Description": "선 4의 표현식 값",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "4231bfd62ddc4cadb454241c96e2a41c",
          "Name": "",
          "Description": "선 5의 표현식 값",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "DesignScript 코드를 직접 작성할 수 있습니다"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.ByCartesianCoordinates@Autodesk.DesignScript.Geometry.CoordinateSystem,double,double,double",
      "Id": "325f30f49fcc4970b71e3e9a3c63ea29",
      "Inputs": [
        {
          "Id": "a70073059f7a43a49ef76388e596a1c9",
          "Name": "coordinateSystem",
          "Description": "상위 좌표계\n\nCoordinateSystem\n기본값 : Autodesk.DesignScript.Geometry.CoordinateSystem.ByOrigin(0, 0, 0)",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "05b40f6fc4c44b158d2fd111e01e6a39",
          "Name": "x",
          "Description": "X coordinate\n\ndouble\n기본값 : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "b249b67f990c42ac93a52cb56db8e8e2",
          "Name": "y",
          "Description": "Y coordinate\n\ndouble\n기본값 : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "52e267e1394947aa9956eb6f402cbd20",
          "Name": "z",
          "Description": "Z coordinate\n\ndouble\n기본값 : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "1f6065257c3d49dc9cff21ffdcb05a98",
          "Name": "Point",
          "Description": "Point at cartesian coordinates",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "CrossProduct",
      "Description": "3개의 데카르트 좌표를 사용하여 지정된 좌표계에서 점을 형성합니다\n\nPoint.ByCartesianCoordinates (coordinateSystem: CoordinateSystem = Autodesk.DesignScript.Geometry.CoordinateSystem.ByOrigin(0, 0, 0), x: double = 0, y: double = 0, z: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSVarArgFunction, DynamoCore",
      "FunctionSignature": "DSCore.List.Join@var[]..[]",
      "FunctionType": "VariableArgument",
      "NodeType": "FunctionNode",
      "Id": "7ddf03be357342ee92a4588e6cd3576e",
      "Inputs": [
        {
          "Id": "6b295b37d42345b084d1ce9f8db05101",
          "Name": "list0",
          "Description": "하나로 결합할 리스트.\n\nvar[]..[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "7e06d2222cc6449790437114bdad9b74",
          "Name": "list1",
          "Description": "var[]..[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "1d64a9f165074401bb4dc9866570aace",
          "Name": "list2",
          "Description": "var[]..[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "e1dd882b09324d41b0e4dcbc0b63c2ff",
          "Name": "list3",
          "Description": "var[]..[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "efcaa8ab62ff4e9c8839e3b5c0b77937",
          "Name": "list4",
          "Description": "var[]..[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "264ebcbe69ba46a89ad698f5ceef3523",
          "Name": "list",
          "Description": "결합된 리스트.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "지정된 모든 리스트를 단일 리스트로 연결합니다.\n\nList.Join (lists: var[]..[]): var[]..[]"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "0..10..1;",
      "Id": "6c2c8cf7cb9b436ea1254c59df783f37",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "3153a50c056a4a86a95bc844ce231e9c",
          "Name": "",
          "Description": "선 1의 표현식 값",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "DesignScript 코드를 직접 작성할 수 있습니다"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.X",
      "Id": "27f3d3446faf463096f95b2a17927ebc",
      "Inputs": [
        {
          "Id": "c546cd546daa450ea4d3fc524a7cb6d5",
          "Name": "point",
          "Description": "Autodesk.DesignScript.Geometry.Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "d0a19582e6ba482b9ca95c2a39c2445f",
          "Name": "double",
          "Description": "double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "점의 X 구성요소 가져오기\n\nPoint.X: double"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.Y",
      "Id": "c7a1e1f55acc4bac8425614ea9fc9103",
      "Inputs": [
        {
          "Id": "c50b0ac11840411b892fd8e4f59a1cf6",
          "Name": "point",
          "Description": "Autodesk.DesignScript.Geometry.Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "84636b44d48744508529d97d70983070",
          "Name": "double",
          "Description": "double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "점의 Y 구성요소 가져오기\n\nPoint.Y: double"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.Z",
      "Id": "412cb22f43e84c50bac48c7ea5c7da30",
      "Inputs": [
        {
          "Id": "3d023d6f8c654d0b959b23ef93a16581",
          "Name": "point",
          "Description": "Autodesk.DesignScript.Geometry.Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "017e46bed9ed47b8ab4b69176033d367",
          "Name": "double",
          "Description": "double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "점의 Z 구성요소 가져오기\n\nPoint.Z: double"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.CoordinateSystem.Origin",
      "Id": "85163f1e95de4da090c774ba10ba0b51",
      "Inputs": [
        {
          "Id": "a6e82775873b4ef38410b27fa1f2704c",
          "Name": "coordinateSystem",
          "Description": "Autodesk.DesignScript.Geometry.CoordinateSystem",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "d898f8b6fb2a4f1d82f49bbfe94dcca1",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "CoordinateSystem 원점을 나타내는 점을 만듭니다.\n\nCoordinateSystem.Origin: Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.PolyCurve.ByPoints@Autodesk.DesignScript.Geometry.Point[],bool",
      "Id": "422945900acf48b892a97dc8f90ced5b",
      "Inputs": [
        {
          "Id": "2160d9c1a6d4484bb7a0fc147f4b0303",
          "Name": "points",
          "Description": "PolyCurve를 만들 점\n\nPoint[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "24f3a9672695435d825b9f608acf40e8",
          "Name": "connectLastToFirst",
          "Description": "마지막 점을 첫 번째 점을 연결하려면 True, 열린 상태로 유지하려면 false\n\nbool\n기본값 : false",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "ae8e19e47eca49ed8459b23007957482",
          "Name": "PolyCurve",
          "Description": "Polycurve created by points",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "점을 연결하여 PolyCurve를 만듭니다. 'connectLastToFirst' 입력을 True로 설정하고 PolyCurve를 닫습니다.\n\nPolyCurve.ByPoints (points: Point[], connectLastToFirst: bool = false): PolyCurve"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Geometry.Transform@Autodesk.DesignScript.Geometry.CoordinateSystem,Autodesk.DesignScript.Geometry.CoordinateSystem",
      "Id": "a6d8514abada46a6827caf1911cceed6",
      "Inputs": [
        {
          "Id": "4938ea2e33644ad0866bfb5037bfc637",
          "Name": "geometry",
          "Description": "Autodesk.DesignScript.Geometry.Geometry",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "ea07447074644f49a3c7ea420098f445",
          "Name": "fromCoordinateSystem",
          "Description": "CoordinateSystem",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "7a60d2374850483f95af8740c60a663b",
          "Name": "contextCoordinateSystem",
          "Description": "CoordinateSystem",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "50e0737fcf4d4296b30a69b3d56d0c81",
          "Name": "Geometry",
          "Description": "변환된 형상.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "이 형상을 소스 CoordinateSystem에서 새 컨텍스트 CoordinateSystem으로 변환합니다.\n\nGeometry.Transform (fromCoordinateSystem: CoordinateSystem, contextCoordinateSystem: CoordinateSystem): Geometry"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.CoordinateSystem.ByOrigin@Autodesk.DesignScript.Geometry.Point",
      "Id": "f6a74209d178465a8597184ba1a1edef",
      "Inputs": [
        {
          "Id": "bb3477197c644c33ba4eab19b94129b8",
          "Name": "origin",
          "Description": "Point\n기본값 : Autodesk.DesignScript.Geometry.Point.ByCoordinates(0, 0, 0)",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "e8794230404c4594b9fe8b8a2eb9ce6a",
          "Name": "CoordinateSystem",
          "Description": "CoordinateSystem",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "입력 점을 원점으로 하고 X 및 Y축이 WCS X 및 Y축으로 설정된 CoordinateSystem을 만듭니다.\n\nCoordinateSystem.ByOrigin (origin: Point = Autodesk.DesignScript.Geometry.Point.ByCoordinates(0, 0, 0)): CoordinateSystem"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Geometry.Transform@Autodesk.DesignScript.Geometry.CoordinateSystem,Autodesk.DesignScript.Geometry.CoordinateSystem",
      "Id": "8cf2d003b0c64a5891087c743f1c6fcc",
      "Inputs": [
        {
          "Id": "8789914929294204b61b1bdd81ffd942",
          "Name": "geometry",
          "Description": "Autodesk.DesignScript.Geometry.Geometry",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "e8305e531597414a96c5527d3eae9ddd",
          "Name": "fromCoordinateSystem",
          "Description": "CoordinateSystem",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "718e0346cf21452b8d911e1c6c0c7ad5",
          "Name": "contextCoordinateSystem",
          "Description": "CoordinateSystem",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "7120afb00ddb49dba9dd39623ab06421",
          "Name": "Geometry",
          "Description": "변환된 형상.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "이 형상을 소스 CoordinateSystem에서 새 컨텍스트 CoordinateSystem으로 변환합니다.\n\nGeometry.Transform (fromCoordinateSystem: CoordinateSystem, contextCoordinateSystem: CoordinateSystem): Geometry"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Geometry.Transform@Autodesk.DesignScript.Geometry.CoordinateSystem,Autodesk.DesignScript.Geometry.CoordinateSystem",
      "Id": "9bf468e58bbe4f36abe6d5526413f6e0",
      "Inputs": [
        {
          "Id": "d90f19639e0a43d4bda77014d46f7b21",
          "Name": "geometry",
          "Description": "Autodesk.DesignScript.Geometry.Geometry",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "c97b4782e5e84f97b3f00c1e95c0c8b4",
          "Name": "fromCoordinateSystem",
          "Description": "CoordinateSystem",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "d72d5d23e7fb4907ac9772b5470b73c6",
          "Name": "contextCoordinateSystem",
          "Description": "CoordinateSystem",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "f468c46b73fe4135b838ab37180ffe40",
          "Name": "Geometry",
          "Description": "변환된 형상.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "이 형상을 소스 CoordinateSystem에서 새 컨텍스트 CoordinateSystem으로 변환합니다.\n\nGeometry.Transform (fromCoordinateSystem: CoordinateSystem, contextCoordinateSystem: CoordinateSystem): Geometry"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.CoordinateSystem.ByOrigin@Autodesk.DesignScript.Geometry.Point",
      "Id": "0fb8b1f7c2db41cd988cc8bec24e3d99",
      "Inputs": [
        {
          "Id": "1420a152ed054f8daa138a7d7bb32133",
          "Name": "origin",
          "Description": "Point\n기본값 : Autodesk.DesignScript.Geometry.Point.ByCoordinates(0, 0, 0)",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "4fe69d60d0ea4d69abe422870666032f",
          "Name": "CoordinateSystem",
          "Description": "CoordinateSystem",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "입력 점을 원점으로 하고 X 및 Y축이 WCS X 및 Y축으로 설정된 CoordinateSystem을 만듭니다.\n\nCoordinateSystem.ByOrigin (origin: Point = Autodesk.DesignScript.Geometry.Point.ByCoordinates(0, 0, 0)): CoordinateSystem"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Surface.ByPerimeterPoints@Autodesk.DesignScript.Geometry.Point[]",
      "Id": "84a3961d2e624559bb3a50472eba8814",
      "Inputs": [
        {
          "Id": "bb14f5144aca42e8957e70d2aa5bc22d",
          "Name": "points",
          "Description": "List of perimeter points\n\nPoint[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "58a010b1d67a4e36a9bfa46593ed9284",
          "Name": "Surface",
          "Description": "Surface created from perimeter points",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "닫힌 다각형의 입력 점을 연결하고 패칭하는 다각형 표면을 만듭니다.\n\nSurface.ByPerimeterPoints (points: Point[]): Surface"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Line.ByStartPointEndPoint@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point",
      "Id": "8c2be8a34b8e495aaa8e694022ba7153",
      "Inputs": [
        {
          "Id": "d96c8866986b41779ecc9e0544272a15",
          "Name": "startPoint",
          "Description": "Line start point\n\nPoint",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "25993a91940e4020a0cc366cd1150a53",
          "Name": "endPoint",
          "Description": "Line end point\n\nPoint",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "91babbbe1a114ef49fd7bd242ce90df9",
          "Name": "Line",
          "Description": "Line from start and end point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "두 입력 점 사이에 직선을 만듭니다.\n\nLine.ByStartPointEndPoint (startPoint: Point, endPoint: Point): Line"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.NurbsSurface.ByPoints@Autodesk.DesignScript.Geometry.Point[][],int,int",
      "Id": "78cca034337f4183b27c01fe9aefb56e",
      "Inputs": [
        {
          "Id": "6aaad27051eb4f4ab1bf07be80cdcaae",
          "Name": "points",
          "Description": "Grid of points for nurbs surface\n\nPoint[][]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "035de79dd84143a19b8d2321298df472",
          "Name": "uDegree",
          "Description": "Degree in u direction\n\nint\n기본값 : 3",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "b28e85ccfcf54cda85e18a0e82050d7f",
          "Name": "vDegree",
          "Description": "Degree in v direction\n\nint\n기본값 : 3",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "e9178c2b061c4b1ea7f6f05970995369",
          "Name": "NurbsSurface",
          "Description": "Nurbs surface created by points",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "지정된 보간 점과 U 및 V 각도를 사용하여 NurbsSurface를 만듭니다. 결과 표면은 모든 점을 통과합니다.\n\nNurbsSurface.ByPoints (points: Point[][], uDegree: int = 3, vDegree: int = 3): NurbsSurface"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.NurbsSurface.ByPoints@Autodesk.DesignScript.Geometry.Point[][],int,int",
      "Id": "c2f324ebe63842c79ef0a235fa6f7772",
      "Inputs": [
        {
          "Id": "215fd36b54d94b0d98dfe32b509fe0ef",
          "Name": "points",
          "Description": "Grid of points for nurbs surface\n\nPoint[][]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "5a49a1bbb623418d882bd100a6ec7e17",
          "Name": "uDegree",
          "Description": "Degree in u direction\n\nint\n기본값 : 3",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "b9363940877b4bd3b90bfec6656cad14",
          "Name": "vDegree",
          "Description": "Degree in v direction\n\nint\n기본값 : 3",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "2b9bae055bf84df0a37853906ca3f2a2",
          "Name": "NurbsSurface",
          "Description": "Nurbs surface created by points",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "지정된 보간 점과 U 및 V 각도를 사용하여 NurbsSurface를 만듭니다. 결과 표면은 모든 점을 통과합니다.\n\nNurbsSurface.ByPoints (points: Point[][], uDegree: int = 3, vDegree: int = 3): NurbsSurface"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSVarArgFunction, DynamoCore",
      "FunctionSignature": "DSCore.List.Join@var[]..[]",
      "FunctionType": "VariableArgument",
      "NodeType": "FunctionNode",
      "Id": "4e939fbd727948898b6379fcd6eb22f6",
      "Inputs": [
        {
          "Id": "f5281de9f8484b239d36707f2e7861af",
          "Name": "list0",
          "Description": "하나로 결합할 리스트.\n\nvar[]..[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "b32bca6f33824f32a5635bf81c73b34f",
          "Name": "list1",
          "Description": "var[]..[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "2f3f161aa82f4ad79a81a2e7895d11db",
          "Name": "list",
          "Description": "결합된 리스트.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "지정된 모든 리스트를 단일 리스트로 연결합니다.\n\nList.Join (lists: var[]..[]): var[]..[]"
    }
  ],
  "Connectors": [
    {
      "Start": "b0898bf4864c4537813c95a07272ca1a",
      "End": "a70073059f7a43a49ef76388e596a1c9",
      "Id": "0711af4d93ad4f2a9a208a34be21106d"
    },
    {
      "Start": "b0898bf4864c4537813c95a07272ca1a",
      "End": "a6e82775873b4ef38410b27fa1f2704c",
      "Id": "46d73f19c4044363b613deb9aae3ec0c"
    },
    {
      "Start": "b0898bf4864c4537813c95a07272ca1a",
      "End": "ea07447074644f49a3c7ea420098f445",
      "Id": "ca51e20a51d04c64a2fa864ddd529961"
    },
    {
      "Start": "b0898bf4864c4537813c95a07272ca1a",
      "End": "718e0346cf21452b8d911e1c6c0c7ad5",
      "Id": "8d6fc85997c14dadbb0c0f6e7ce99406"
    },
    {
      "Start": "7c11aee3e4314cb3abc3cc0cd3ebe509",
      "End": "8ea06d58a3ba46359a23c92fd7f47149",
      "Id": "acb7f18aa8244362bb7d75f48c02c8a6"
    },
    {
      "Start": "636083cd8ab44af7ad777c5a7348b31a",
      "End": "6b295b37d42345b084d1ce9f8db05101",
      "Id": "23e701d2135741ca82527a48f6cbc7b9"
    },
    {
      "Start": "fb8e311a6f484d46bb8be142a68d75f7",
      "End": "7e06d2222cc6449790437114bdad9b74",
      "Id": "3d00391505474915a7d3e9c1ce703710"
    },
    {
      "Start": "239feb11b141466594bd8fa425590541",
      "End": "1d64a9f165074401bb4dc9866570aace",
      "Id": "706efb938a6c49598f274f633267ccd1"
    },
    {
      "Start": "f7de09c4355a49a38b434bc1bdd44742",
      "End": "e1dd882b09324d41b0e4dcbc0b63c2ff",
      "Id": "fd3d6d853eb34d83aee87abcc3215c7b"
    },
    {
      "Start": "4231bfd62ddc4cadb454241c96e2a41c",
      "End": "efcaa8ab62ff4e9c8839e3b5c0b77937",
      "Id": "25c7e17113ad401daede65cac3d9ba67"
    },
    {
      "Start": "1f6065257c3d49dc9cff21ffdcb05a98",
      "End": "4938ea2e33644ad0866bfb5037bfc637",
      "Id": "f92c6d37e90b4bd084c7712de14b7963"
    },
    {
      "Start": "1f6065257c3d49dc9cff21ffdcb05a98",
      "End": "d96c8866986b41779ecc9e0544272a15",
      "Id": "32c900aaf87e489a9b69f44e41f76561"
    },
    {
      "Start": "1f6065257c3d49dc9cff21ffdcb05a98",
      "End": "f5281de9f8484b239d36707f2e7861af",
      "Id": "920be0ca30fb4bda9579373f9128ec8d"
    },
    {
      "Start": "264ebcbe69ba46a89ad698f5ceef3523",
      "End": "eadfe5dff8454c01984d43280ff58daf",
      "Id": "bdd5089ad6c14d9892429fe2e9e10e4b"
    },
    {
      "Start": "3153a50c056a4a86a95bc844ce231e9c",
      "End": "b249b67f990c42ac93a52cb56db8e8e2",
      "Id": "80f925d7ed274908b5f11b5ff1d7a07d"
    },
    {
      "Start": "3153a50c056a4a86a95bc844ce231e9c",
      "End": "05b40f6fc4c44b158d2fd111e01e6a39",
      "Id": "4434c0c60eb44db78e4712419c1c90be"
    },
    {
      "Start": "d898f8b6fb2a4f1d82f49bbfe94dcca1",
      "End": "c546cd546daa450ea4d3fc524a7cb6d5",
      "Id": "543b003ab1c64e01b87d2bcb6e927977"
    },
    {
      "Start": "d898f8b6fb2a4f1d82f49bbfe94dcca1",
      "End": "c50b0ac11840411b892fd8e4f59a1cf6",
      "Id": "fedcbd6e0c8c445abcdfca07faa60fb1"
    },
    {
      "Start": "d898f8b6fb2a4f1d82f49bbfe94dcca1",
      "End": "3d023d6f8c654d0b959b23ef93a16581",
      "Id": "20c36c24ceea4a668966921938bc147b"
    },
    {
      "Start": "ae8e19e47eca49ed8459b23007957482",
      "End": "8789914929294204b61b1bdd81ffd942",
      "Id": "332a8c8ef8c34837a480122d59fcfcdb"
    },
    {
      "Start": "50e0737fcf4d4296b30a69b3d56d0c81",
      "End": "2160d9c1a6d4484bb7a0fc147f4b0303",
      "Id": "4d135947978945f8b3f893994df6cafa"
    },
    {
      "Start": "50e0737fcf4d4296b30a69b3d56d0c81",
      "End": "25993a91940e4020a0cc366cd1150a53",
      "Id": "90236e47f2cb4275adf2adfe48f05ffc"
    },
    {
      "Start": "50e0737fcf4d4296b30a69b3d56d0c81",
      "End": "b32bca6f33824f32a5635bf81c73b34f",
      "Id": "f16d991c0c6d419bb72fc074e3c867f9"
    },
    {
      "Start": "e8794230404c4594b9fe8b8a2eb9ce6a",
      "End": "7a60d2374850483f95af8740c60a663b",
      "Id": "ff8575f31eda45b2b152f9b207585405"
    },
    {
      "Start": "e8794230404c4594b9fe8b8a2eb9ce6a",
      "End": "e8305e531597414a96c5527d3eae9ddd",
      "Id": "25fb4accd3ec400e8c6ebc70d9a6dbb4"
    },
    {
      "Start": "4fe69d60d0ea4d69abe422870666032f",
      "End": "c97b4782e5e84f97b3f00c1e95c0c8b4",
      "Id": "9dee20d3cda64222a00276d553e3d038"
    },
    {
      "Start": "4fe69d60d0ea4d69abe422870666032f",
      "End": "d72d5d23e7fb4907ac9772b5470b73c6",
      "Id": "09820d0993da42aabf56120782f13a5e"
    },
    {
      "Start": "2f3f161aa82f4ad79a81a2e7895d11db",
      "End": "215fd36b54d94b0d98dfe32b509fe0ef",
      "Id": "e3da67ab180b4deca6591fccef53c052"
    }
  ],
  "Dependencies": [],
  "NodeLibraryDependencies": [],
  "Thumbnail": "",
  "GraphDocumentationURL": null,
  "ExtensionWorkspaceData": [
    {
      "ExtensionGuid": "28992e1d-abb9-417f-8b1b-05e053bee670",
      "Name": "Properties",
      "Version": "2.12",
      "Data": {}
    }
  ],
  "Author": "",
  "Linting": {
    "activeLinter": "없음",
    "activeLinterId": "7b75fb44-43fd-4631-a878-29f4d5d8399a",
    "warningCount": 0,
    "errorCount": 0
  },
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": true,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.12.0.5650",
      "RunType": "Automatic",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "배경 미리보기",
      "EyeX": -19.805276870727539,
      "EyeY": 28.412677764892578,
      "EyeZ": 29.375423431396484,
      "LookX": 19.933914184570313,
      "LookY": -13.346225738525391,
      "LookZ": -30.825273513793945,
      "UpX": 0.071817837655544281,
      "UpY": 0.99121552705764771,
      "UpZ": -0.11105859279632568
    },
    "NodeViews": [
      {
        "ShowGeometry": true,
        "Name": "CoordinateSystem.ByPlane",
        "Id": "8709a61bede04d499643d6152eb8306f",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 850.87986684703048,
        "Y": -26.236965645095211
      },
      {
        "ShowGeometry": false,
        "Name": "Plane.ByBestFitThroughPoints",
        "Id": "8c0d13e9f4d94603a8b97a3c7e8fcde4",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 492.12048827219485,
        "Y": 98.879964211033581
      },
      {
        "ShowGeometry": false,
        "Name": "Code Block",
        "Id": "5da7d3f3bb72442bb160b8f9ce4772a2",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 33.186793635098638,
        "Y": 120.91289065087105
      },
      {
        "ShowGeometry": true,
        "Name": "Point.ByCartesianCoordinates",
        "Id": "325f30f49fcc4970b71e3e9a3c63ea29",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1239.5109861243909,
        "Y": 195.42578130174184
      },
      {
        "ShowGeometry": false,
        "Name": "List.Join",
        "Id": "7ddf03be357342ee92a4588e6cd3576e",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 343.82661858579615,
        "Y": 104.81101377959311
      },
      {
        "ShowGeometry": true,
        "Name": "Code Block",
        "Id": "6c2c8cf7cb9b436ea1254c59df783f37",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 970.0,
        "Y": 343.0
      },
      {
        "ShowGeometry": true,
        "Name": "Point.X",
        "Id": "27f3d3446faf463096f95b2a17927ebc",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1439.2393801244677,
        "Y": -189.22604910424582
      },
      {
        "ShowGeometry": true,
        "Name": "Point.Y",
        "Id": "c7a1e1f55acc4bac8425614ea9fc9103",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1433.9474161121821,
        "Y": -100.99263067007541
      },
      {
        "ShowGeometry": true,
        "Name": "Point.Z",
        "Id": "412cb22f43e84c50bac48c7ea5c7da30",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1429.014290613741,
        "Y": -11.363903055971036
      },
      {
        "ShowGeometry": true,
        "Name": "CoordinateSystem.Origin",
        "Id": "85163f1e95de4da090c774ba10ba0b51",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1104.0754713213896,
        "Y": -166.30210251158258
      },
      {
        "ShowGeometry": true,
        "Name": "PolyCurve.ByPoints",
        "Id": "422945900acf48b892a97dc8f90ced5b",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 2443.3956110859131,
        "Y": 303.92624894961955
      },
      {
        "ShowGeometry": true,
        "Name": "Geometry.Transform",
        "Id": "a6d8514abada46a6827caf1911cceed6",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1777.9367887508013,
        "Y": 298.14830435808057
      },
      {
        "ShowGeometry": true,
        "Name": "CoordinateSystem.ByOrigin",
        "Id": "f6a74209d178465a8597184ba1a1edef",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1263.4821972318816,
        "Y": 547.60567355519242
      },
      {
        "ShowGeometry": true,
        "Name": "Geometry.Transform",
        "Id": "8cf2d003b0c64a5891087c743f1c6fcc",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 2870.2962518618647,
        "Y": 21.248341741956892
      },
      {
        "ShowGeometry": false,
        "Name": "Geometry.Transform",
        "Id": "9bf468e58bbe4f36abe6d5526413f6e0",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 435.71307355755016,
        "Y": 506.36122460069708
      },
      {
        "ShowGeometry": false,
        "Name": "CoordinateSystem.ByOrigin",
        "Id": "0fb8b1f7c2db41cd988cc8bec24e3d99",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 95.803168499996559,
        "Y": 544.59715667055661
      },
      {
        "ShowGeometry": true,
        "Name": "Surface.ByPerimeterPoints",
        "Id": "84a3961d2e624559bb3a50472eba8814",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1669.6890400624156,
        "Y": 723.89844659499818
      },
      {
        "ShowGeometry": true,
        "Name": "Line.ByStartPointEndPoint",
        "Id": "8c2be8a34b8e495aaa8e694022ba7153",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1958.1094441689174,
        "Y": -464.31550114408333
      },
      {
        "ShowGeometry": true,
        "Name": "NurbsSurface.ByPoints",
        "Id": "78cca034337f4183b27c01fe9aefb56e",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1965.5077288296952,
        "Y": 45.472070762643284
      },
      {
        "ShowGeometry": false,
        "Name": "NurbsSurface.ByPoints",
        "Id": "c2f324ebe63842c79ef0a235fa6f7772",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 2231.0880812824134,
        "Y": -638.72874080974952
      },
      {
        "ShowGeometry": true,
        "Name": "List.Join",
        "Id": "4e939fbd727948898b6379fcd6eb22f6",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 2159.312033409924,
        "Y": -287.80034616577717
      }
    ],
    "Annotations": [
      {
        "Id": "004ed51b9ad64eeba9d346e6b315c238",
        "Title": "<그룹 제목을 수정하려면 여기를 클릭하십시오.>",
        "Nodes": [
          "8709a61bede04d499643d6152eb8306f",
          "325f30f49fcc4970b71e3e9a3c63ea29",
          "6c2c8cf7cb9b436ea1254c59df783f37",
          "27f3d3446faf463096f95b2a17927ebc",
          "c7a1e1f55acc4bac8425614ea9fc9103",
          "412cb22f43e84c50bac48c7ea5c7da30",
          "85163f1e95de4da090c774ba10ba0b51",
          "422945900acf48b892a97dc8f90ced5b",
          "a6d8514abada46a6827caf1911cceed6",
          "f6a74209d178465a8597184ba1a1edef",
          "8cf2d003b0c64a5891087c743f1c6fcc"
        ],
        "Left": 840.87986684703048,
        "Top": -242.42604910424581,
        "Width": 2375.4163850148343,
        "Height": 882.63172265943831,
        "FontSize": 36.0,
        "InitialTop": -189.22604910424582,
        "InitialHeight": 859.43172265943826,
        "TextblockHeight": 43.2,
        "Background": "#FFC1D676"
      }
    ],
    "X": -866.07790679812251,
    "Y": 68.3582518966395,
    "Zoom": 0.58077495019560987
  }
}