{
  "Uuid": "daf6acbe-4554-47fd-8643-156da99488db",
  "IsCustomNode": false,
  "Description": "",
  "Name": "meetEach",
  "ElementResolver": {
    "ResolutionMap": {}
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "PythonNodeModels.PythonNode, PythonNodeModels",
      "NodeType": "PythonScriptNode",
      "Code": "# Load the Python Standard and DesignScript Libraries\r\nimport sys\r\nimport clr\r\nclr.AddReference('ProtoGeometry')\r\nfrom Autodesk.DesignScript.Geometry import *\r\n\r\n# The inputs to this node will be stored as a list in the IN variables.\r\ndataEnteringNode = IN\r\n\r\n# Place your code below this line\r\n\r\n# Assign your output to the OUT variable.\r\nOUT = dir(Cuboid)",
      "Engine": "CPython3",
      "VariableInputPorts": true,
      "Id": "00fbe507d4dc4fe4b4cf9ea31f3c307e",
      "Inputs": [
        {
          "Id": "8366166d46d7451ca890722fcbbbb123",
          "Name": "IN[0]",
          "Description": "Input #0",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "680391b8f6504c5d8b75d67b7f3c9941",
          "Name": "OUT",
          "Description": "Result of the python script",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Runs an embedded Python script."
    },
    {
      "ConcreteType": "PythonNodeModels.PythonNode, PythonNodeModels",
      "NodeType": "PythonScriptNode",
      "Code": "# Load the Python Standard and DesignScript Libraries\r\nimport sys\r\nimport clr\r\nclr.AddReference('ProtoGeometry')\r\nfrom Autodesk.DesignScript.Geometry import *\r\n\r\n# The inputs to this node will be stored as a list in the IN variables.\r\ndataEnteringNode = IN\r\nels = IN[0]\r\n\r\n# Place your code below this line\r\n\r\n## 두가지 형상을 서로의 최단거리 선분의 중점에서 만나도록 하는 코드\r\ndef meetEach(els):\r\n    if len(els) == 3 and els[2]:\r\n        shortPoints = [els[0].ClosestPointTo(els[1]), els[1].ClosestPointTo(els[0])]\r\n        _vec = Vector.ByTwoPoints(shortPoints[1], shortPoints[0])\r\n        transGeos  = [els[0], els[1].Translate(_vec)]\r\n    else:\r\n        shortPoints = [els[0].ClosestPointTo(els[1]), els[1].ClosestPointTo(els[0])]\r\n        _line = Line.ByStartPointEndPoint(shortPoints[0], shortPoints[1])\r\n        midPoint = _line.PointAtParameter(0.5)\r\n        _vecs = [Vector.ByTwoPoints(shortPoints[0], midPoint), Vector.ByTwoPoints(shortPoints[1], midPoint)]\r\n        transGeos  = [els[0].Translate(_vecs[0]), els[1].Translate(_vecs[1])]\r\n        \r\n    return transGeos\r\n\r\nresult = meetEach(els)\r\n#result = el.ComputeHashCode()\r\n# Assign your output to the OUT variable.\r\nOUT = result",
      "Engine": "CPython3",
      "VariableInputPorts": true,
      "Id": "24c80c2132394cacb1ba1e820de594eb",
      "Inputs": [
        {
          "Id": "3c0f3695b77446cc931e974478fa6d2a",
          "Name": "IN[0]",
          "Description": "Input #0",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "d3e377f1db7c4239bbe526b840d1e9e0",
          "Name": "OUT",
          "Description": "Result of the python script",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Runs an embedded Python script."
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Cuboid.ByLengths@Autodesk.DesignScript.Geometry.Point,double,double,double",
      "Id": "799060eb30604b6381a2499cf7242ee7",
      "Inputs": [
        {
          "Id": "159fc23ce5b74dea87a9cf04808a0884",
          "Name": "origin",
          "Description": "Origin point\n\nPoint\nDefault value : Autodesk.DesignScript.Geometry.Point.ByCoordinates(0, 0, 0)",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "2c4e114183d34507aa5fa37dc271cf73",
          "Name": "width",
          "Description": "Width of cuboid\n\ndouble\nDefault value : 1",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "cf821b616c114356b6933265802d2530",
          "Name": "length",
          "Description": "Length of cuboid\n\ndouble\nDefault value : 1",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "01414782eaa54d46bbd56bcb33dfe63d",
          "Name": "height",
          "Description": "Height of cuboid\n\ndouble\nDefault value : 1",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "82a7a23f27344e52a40ddc42e7fef975",
          "Name": "Cuboid",
          "Description": "Cuboid created by lengths",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a Cuboid centered at input Point, with specified width, length, and height.\n\nCuboid.ByLengths (origin: Point = Autodesk.DesignScript.Geometry.Point.ByCoordinates(0, 0, 0), width: double = 1, length: double = 1, height: double = 1): Cuboid"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double",
      "Id": "617b6483cafc44dea673f6151efdaaf7",
      "Inputs": [
        {
          "Id": "a2e2e69cc61a419aad85d78d30618e33",
          "Name": "x",
          "Description": "X coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "9d79af28aac24401a4fe7c58420d54bb",
          "Name": "y",
          "Description": "Y coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "fb5cd3404d014648a6db2dfd2cd6d220",
          "Name": "z",
          "Description": "Z coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "da5b37c3171b484092c471e7930de102",
          "Name": "Point",
          "Description": "Point created by coordinates",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Form a Point given 3 cartesian coordinates\n\nPoint.ByCoordinates (x: double = 0, y: double = 0, z: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "10;\n1.4;",
      "Id": "1aefbf6527604293acc7057448cc8ee6",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "f61c381d4f5942178a75ca3cff554f9f",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "210131d93c104035b2ecf4f54cbc177a",
          "Name": "",
          "Description": "Value of expression at line 2",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Sphere.ByCenterPointRadius@Autodesk.DesignScript.Geometry.Point,double",
      "Id": "8bc75efda545434ba5e1042ae9ba6ef7",
      "Inputs": [
        {
          "Id": "26d7f5f75922431a9125754349cd8714",
          "Name": "centerPoint",
          "Description": "Point\nDefault value : Autodesk.DesignScript.Geometry.Point.ByCoordinates(0, 0, 0)",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "f747078117b246e1b75823a98f7338b8",
          "Name": "radius",
          "Description": "double\nDefault value : 1",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "0cb85b520b5d45a081e615cd1d8a392f",
          "Name": "Sphere",
          "Description": "Sphere",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a Solid Sphere cetered at the input Point, with given radius.\n\nSphere.ByCenterPointRadius (centerPoint: Point = Autodesk.DesignScript.Geometry.Point.ByCoordinates(0, 0, 0), radius: double = 1): Sphere"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double",
      "Id": "cff4ac1d42fd473f98614637a05fed44",
      "Inputs": [
        {
          "Id": "0671d42cedf24bb4b465f4c728601a0f",
          "Name": "x",
          "Description": "X coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "f99ce53213584be1b58d445a2982618f",
          "Name": "y",
          "Description": "Y coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "a36439d9f5f14d0880a4e4c3e639a447",
          "Name": "z",
          "Description": "Z coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "98781be38d2944638b2de47df814ed58",
          "Name": "Point",
          "Description": "Point created by coordinates",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Form a Point given 3 cartesian coordinates\n\nPoint.ByCoordinates (x: double = 0, y: double = 0, z: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "-10;",
      "Id": "216120a9dc6a439eb51ee6b9e29f6e9f",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "110457e194674f69a144fa01da8dec31",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Curve.PointAtParameter@double",
      "Id": "fd4d4804bc9d41b899b0c9d19ea459b5",
      "Inputs": [
        {
          "Id": "c66afe4e185549378665d6979a09a193",
          "Name": "curve",
          "Description": "Autodesk.DesignScript.Geometry.Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "28f25cd2b397404fa3ef2c7186529a72",
          "Name": "param",
          "Description": "The parameter at which to evaluate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "00e9c5a3b73f4c38903938e9fc3a65a8",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get a Point on the Curve at a specified parameter between StartParameter() and EndParameter()\n\nCurve.PointAtParameter (param: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSVarArgFunction, DynamoCore",
      "FunctionSignature": "DSCore.List.Join@var[]..[]",
      "FunctionType": "VariableArgument",
      "NodeType": "FunctionNode",
      "Id": "788a0115719147588d3cfe89b57b9605",
      "Inputs": [
        {
          "Id": "84eefe9a0a21475aa8e10eddd9fa562c",
          "Name": "list0",
          "Description": "Lists to join into one.\n\nvar[]..[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "a3fb97e4597f4cd79e1d8622ecacdc1c",
          "Name": "list1",
          "Description": "var[]..[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "76c4d2c1ba53449daa23564bb53dba35",
          "Name": "list2",
          "Description": "var[]..[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "572133681f4646fa8248a2dc055d72e8",
          "Name": "list",
          "Description": "Joined list.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Concatenates all given lists into a single list.\n\nList.Join (lists: var[]..[]): var[]..[]"
    },
    {
      "ConcreteType": "CoreNodeModels.Input.BoolSelector, CoreNodeModels",
      "NodeType": "BooleanInputNode",
      "InputValue": false,
      "Id": "bb0135b02ef14e85bac4a946787c8438",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "ed273571d8b24d69b62dbbd63efaaab8",
          "Name": "",
          "Description": "Boolean",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Selection between a true and false."
    },
    {
      "ConcreteType": "PythonNodeModels.PythonNode, PythonNodeModels",
      "NodeType": "PythonScriptNode",
      "Code": "# Load the Python Standard and DesignScript Libraries\r\nimport sys\r\nimport clr\r\nclr.AddReference('ProtoGeometry')\r\nfrom Autodesk.DesignScript.Geometry import *\r\n\r\n# The inputs to this node will be stored as a list in the IN variables.\r\ndataEnteringNode = IN\r\nels = IN[0]\r\n\r\n# Place your code below this line\r\n\r\n## 두가지 형상을 서로의 최단거리 선분의 중점에서 만나도록 하는 코드\r\ndef meetEach(els):\r\n    if len(els) == 3 and els[2]:\r\n        shortPoints = [els[0].ClosestPointTo(els[1]), els[1].ClosestPointTo(els[0])]\r\n#        _vec = Vector.ByTwoPoints(shortPoints[1], shortPoints[0])\r\n        transGeos  = shortPoints#[els[0], els[1].Translate(_vec)]\r\n    else:\r\n        shortPoints = [els[0].ClosestPointTo(els[1]), els[1].ClosestPointTo(els[0])]\r\n#        _line = Line.ByStartPointEndPoint(shortPoints[0], shortPoints[1])\r\n#        midPoint = _line.PointAtParameter(0.5)\r\n#        _vecs = [Vector.ByTwoPoints(shortPoints[0], midPoint), Vector.ByTwoPoints(shortPoints[1], midPoint)]\r\n        transGeos  = shortPoints#[els[0].Translate(_vecs[0]), els[1].Translate(_vecs[1])]\r\n        \r\n    return transGeos\r\n\r\nresult = meetEach(els)\r\n#result = el.ComputeHashCode()\r\n# Assign your output to the OUT variable.\r\nOUT = result",
      "Engine": "CPython3",
      "VariableInputPorts": true,
      "Id": "068039f5b1c04bf485ae8be36865f623",
      "Inputs": [
        {
          "Id": "b90797aaa2084a3aa8e37be173306d5b",
          "Name": "IN[0]",
          "Description": "Input #0",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "338a1d30af8449709ba9cee80e8ef81a",
          "Name": "OUT",
          "Description": "Result of the python script",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Runs an embedded Python script."
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Geometry.ClosestPointTo@Autodesk.DesignScript.Geometry.Geometry",
      "Id": "d2fa86abc7444bf59bf74a7c3559a7b7",
      "Inputs": [
        {
          "Id": "d2dbb053391b448abf00c4154d55e3fe",
          "Name": "geometry",
          "Description": "Autodesk.DesignScript.Geometry.Geometry",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "01303d67685c450481ae7ae79bf507d7",
          "Name": "other",
          "Description": "Geometry",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "8ca86eba78b343db90502587e6013d46",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Obtain the closest Point on this Geometry to the other\n\nGeometry.ClosestPointTo (other: Geometry): Point"
    }
  ],
  "Connectors": [
    {
      "Start": "82a7a23f27344e52a40ddc42e7fef975",
      "End": "a3fb97e4597f4cd79e1d8622ecacdc1c",
      "Id": "0372124d39114aaca3d32fcf1189b319"
    },
    {
      "Start": "82a7a23f27344e52a40ddc42e7fef975",
      "End": "01303d67685c450481ae7ae79bf507d7",
      "Id": "9c1fc38463cf4be8b6284ab6f3d368e8"
    },
    {
      "Start": "da5b37c3171b484092c471e7930de102",
      "End": "159fc23ce5b74dea87a9cf04808a0884",
      "Id": "df49799429874efcbf3b54b0211b747d"
    },
    {
      "Start": "210131d93c104035b2ecf4f54cbc177a",
      "End": "9d79af28aac24401a4fe7c58420d54bb",
      "Id": "1ac88aed15454157b7be5f44d2810b1d"
    },
    {
      "Start": "0cb85b520b5d45a081e615cd1d8a392f",
      "End": "84eefe9a0a21475aa8e10eddd9fa562c",
      "Id": "700fa1c3de914caca97d13e25f90d3cb"
    },
    {
      "Start": "0cb85b520b5d45a081e615cd1d8a392f",
      "End": "d2dbb053391b448abf00c4154d55e3fe",
      "Id": "1fe228ddfee84d8b8173d77891d4c4eb"
    },
    {
      "Start": "98781be38d2944638b2de47df814ed58",
      "End": "26d7f5f75922431a9125754349cd8714",
      "Id": "53e9fa38574948aabffdb757b91afccb"
    },
    {
      "Start": "572133681f4646fa8248a2dc055d72e8",
      "End": "3c0f3695b77446cc931e974478fa6d2a",
      "Id": "1a2a01c8c994478f948ffe707c049712"
    },
    {
      "Start": "572133681f4646fa8248a2dc055d72e8",
      "End": "b90797aaa2084a3aa8e37be173306d5b",
      "Id": "31580c73fb69451c99b3d0c8435b6992"
    },
    {
      "Start": "ed273571d8b24d69b62dbbd63efaaab8",
      "End": "76c4d2c1ba53449daa23564bb53dba35",
      "Id": "b9e60e5f4738442d91916f7eff13b5de"
    }
  ],
  "Dependencies": [],
  "NodeLibraryDependencies": [],
  "Thumbnail": "",
  "GraphDocumentationURL": null,
  "ExtensionWorkspaceData": [
    {
      "ExtensionGuid": "28992e1d-abb9-417f-8b1b-05e053bee670",
      "Name": "Properties",
      "Version": "2.12",
      "Data": {}
    },
    {
      "ExtensionGuid": "DFBD9CC0-DB40-457A-939E-8C8555555A9D",
      "Name": "Generative Design",
      "Version": "1.10",
      "Data": {}
    }
  ],
  "Author": "",
  "Linting": {
    "activeLinter": "None",
    "activeLinterId": "7b75fb44-43fd-4631-a878-29f4d5d8399a",
    "warningCount": 0,
    "errorCount": 0
  },
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": true,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.12.0.5650",
      "RunType": "Automatic",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Background Preview",
      "EyeX": 3.7390055656433105,
      "EyeY": 0.87090981006622314,
      "EyeZ": -0.64800846576690674,
      "LookX": -4.2928276062011719,
      "LookY": -1.5246410369873047,
      "LookZ": -1.6212104558944702,
      "UpX": -0.097788281738758087,
      "UpY": 0.99452179670333862,
      "UpZ": -0.036930400878190994
    },
    "NodeViews": [
      {
        "ShowGeometry": true,
        "Name": "Python Script",
        "Id": "00fbe507d4dc4fe4b4cf9ea31f3c307e",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 595.71891230746473,
        "Y": 663.2575244771707
      },
      {
        "ShowGeometry": false,
        "Name": "Python Script",
        "Id": "24c80c2132394cacb1ba1e820de594eb",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1182.873565895984,
        "Y": 265.60062376991732
      },
      {
        "ShowGeometry": false,
        "Name": "Cuboid.ByLengths",
        "Id": "799060eb30604b6381a2499cf7242ee7",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 541.4528409864098,
        "Y": 17.618776429212161
      },
      {
        "ShowGeometry": false,
        "Name": "Point.ByCoordinates",
        "Id": "617b6483cafc44dea673f6151efdaaf7",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 302.69331319115787,
        "Y": -12.4809538884721
      },
      {
        "ShowGeometry": false,
        "Name": "Code Block",
        "Id": "1aefbf6527604293acc7057448cc8ee6",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 145.0,
        "Y": 73.0
      },
      {
        "ShowGeometry": false,
        "Name": "Sphere.ByCenterPointRadius",
        "Id": "8bc75efda545434ba5e1042ae9ba6ef7",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 449.76157046087621,
        "Y": 240.38735042178138
      },
      {
        "ShowGeometry": false,
        "Name": "Point.ByCoordinates",
        "Id": "cff4ac1d42fd473f98614637a05fed44",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 134.70053016616271,
        "Y": 328.3617261519471
      },
      {
        "ShowGeometry": false,
        "Name": "Code Block",
        "Id": "216120a9dc6a439eb51ee6b9e29f6e9f",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -22.992783024995276,
        "Y": 413.84268004041917
      },
      {
        "ShowGeometry": true,
        "Name": "Curve.PointAtParameter",
        "Id": "fd4d4804bc9d41b899b0c9d19ea459b5",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1145.7495269863703,
        "Y": 874.54165705556716
      },
      {
        "ShowGeometry": false,
        "Name": "List.Join",
        "Id": "788a0115719147588d3cfe89b57b9605",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 887.47843563519712,
        "Y": 44.37564659600443
      },
      {
        "ShowGeometry": true,
        "Name": "Boolean",
        "Id": "bb0135b02ef14e85bac4a946787c8438",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 777.60054546877848,
        "Y": 352.92457389543807
      },
      {
        "ShowGeometry": false,
        "Name": "Python Script",
        "Id": "068039f5b1c04bf485ae8be36865f623",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1114.3201649790676,
        "Y": -33.792606485287962
      },
      {
        "ShowGeometry": true,
        "Name": "Geometry.ClosestPointTo",
        "Id": "d2fa86abc7444bf59bf74a7c3559a7b7",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 848.488826487133,
        "Y": -302.4050570838254
      }
    ],
    "Annotations": [],
    "X": -550.42467937966921,
    "Y": 465.31512573272317,
    "Zoom": 1.2220365811452965
  }
}